### PR TITLE
Leaderboard results pills

### PR DESCRIPTION
**Pull request by jjmountain**
Implemented `ResultsCard`, `MatchPredictions` component designs as suggested by @trouni

### CODE REVIEW

**Review by trouni — APPROVED** [review]
Awesome, thanks! 👏

**Comment by trouni** [comment]
@jjmountain Actually, I've got this error in the console that you should probably fix before merging:
Octacle

**Comment by jjmountain** [comment]
> @jjmountain Actually, I've got this error in the console that you should probably fix before merging: Octacle

Ah woops, that was a silly one. Fixed ✅

**Comment by trouni** [comment]
Ok feel free to merge if that's fixed 👍

**Pull request merged**
