### PR TITLE
Leaderboard results bars

### PR DESCRIPTION
**Pull request by jjmountain**
added leaderboard results bars on MatchPredictions component.

### CODE REVIEW

**Comment by jjmountain** [comment]
@trouni Ok I think I requested merge into the correct branch this time 😅

Sorry for the mistake before.

**Comment by trouni** [comment]
No worries, you can actually click on Edit on top and change the base branch

**Comment by jjmountain** [comment]
Unfortunately I just realized that the MatchPredictions only works from the Results tab. It is not rendering in the Predictions tab. It's hard to diagnose at first glance as we never get past the bouncing ball, but my guess is that the user predictions data is not available in the predictions tab in the same data structure.

**Comment by trouni** [comment]
Thanks @jjmountain! For the colors, I was a bit confused as to what they meant until I looked at the code. I think it also distracts from the actual result of the game and who got the right or wrong predictions.

I think it would be easier to understand if we did the following:
- only color the column with the right choice using our `prediction-correct` green color
- wrong predictions just get the current DRAW grey to not attract too much attention to them

What do you think? @dmbf29 any other feedback?

**Comment by jjmountain** [comment]
@trouni thanks for the feedback!

I see what you mean and yes agree it makes sense to use those colors for the bars in the results tab.

Perhaps the colors could only be used when the matches are upcoming and don’t have results yet. What do you think? I actually took inspiration from google who use colors for team odds.

**Comment by trouni** [comment]
The problem for me was just that it wasn't clear at all that the blue was meant to represent Japan or the green was representing Morocco, etc.

We could probably just keep everything grey until we know the final result, or have a 50% opacity green on the expected winning choice (if the scores were to stay the same).

> Unfortunately I just realized that the MatchPredictions only works from the Results tab. It is not rendering in the Predictions tab. It's hard to diagnose at first glance as we never get past the bouncing ball, but my guess is that the user predictions data is not available in the predictions tab in the same data structure.

Yes, they intentionally should not show up in the Predict tab, since that tab is not linked to a specific leaderboard anyway. That's why we split the navigation to have a dedicated results page.

**Comment by trouni** [comment]
Also, another suggestion: I think we should set a minimum width for each of the columns, and always show all three of them (even if it's at 0%). It's a bit harder to read when one of the columns is missing because we need to figure out which one is not displayed. Having all three columns all the time would help with always knowing what the left, middle and right columns represent.

**Comment by jjmountain** [comment]
@trouni, do you mean like this? 

Personally I find it easy to tell which is which but I understand it may be clearer with what you are saying. I was trying to go for less repetition of the team names too. 



Also the colors I chose were the official team colors (either uniform or badge), but sure we can change. 

Care to weigh in @dmbf29?

**Comment by jjmountain** [comment]
In this example it's easier to see how your suggestion would make it clearer, as the draw predictions wouldn't be off on the right

**Comment by trouni** [comment]
Hey @jjmountain I've been playing with designs in the browser to try and find a layout that would avoid repeating the choice names and balance the display a little bit.

It's quite different from the MatchCard component though, so you could also create a new `ResultCard` component instead of trying to modify the original one if it's simpler!

### All choices present, user made the correct prediction

Cursor_and_Octacle_🔊

FYI, I've got this for the user pill:
```css
font-size: 0.675rem;
border: solid 0.5px;
border-radius: 2em;
padding: 0.1em 0.5em;
line-height: 1.2em;
margin: 0.1em;
font-weight: 100;
text-overflow: ellipsis;
white-space: nowrap;
overflow: hidden;
```

### One choice has no predictions, user made wrong prediction

Cursor_and_Octacle_🔊


I've just added a `min-width: 2em;` so that the 0% still shows.

**Comment by jjmountain** [comment]
@trouni This is definitely a better approach I think. Thanks for taking the time to work out the design. 

I'll make a new component `ResultCard` and break down some of the common elements between this and `MatchCard` into their own components to DRY it out a bit.

**Comment by trouni** [comment]
Closing this one since we have #224

**Pull request closed without merging**
