### PR TITLE
New feature: Leaderboard Results

### LINKED ISSUE #99: Add sliding screens to leaderboard swiping
This will be useful now that we want to add a global leaderboard, meaning that everybody will have more than one leaderboard.

### LINKED ISSUE #154: Display all players predictions for all past and ongoing matches
Maybe on the Leaderboard#show page?

### LINKED ISSUE #206: Show percentages of predictions for each pick (team A / team B / draw) for ongoing and completed games

### LINKED ISSUE #208: Rework the navigation
We will be re-working the navigation to facilitate the splitting of the features:
- Remove the "Back" button
- Rename Matches to Predictions (change the icon as well?)
- Create a new nav item called "Results" which will have the same layout as the Leaderboards, but instead of the rankings, it will show the user predictions per match per leaderboard (will be implemented in #135)

### PR DESCRIPTION
**Pull request by trouni**
The work from dmbf29/predictor-api#110 is required for this PR

[Netlify deploy preview](https://deploy-preview-212--octacle.netlify.app/).

Work that needs to be done for this feature:
- [x] #208 
- [x] #154

Fixes #99, fixes #154, fixes #206, fixes #208

### CODE REVIEW

**Comment by dmbf29** [comment]
Screen Shot 2022-12-06 at 13 46 08

this isn't very constructive, but it seems a tad strange to now have a combo between the red and the green on incorrect predictions

**Comment by dmbf29** [comment]
would keeping the red border and making your name red be more explicit? maybe something like 👇 

Screen Shot 2022-12-06 at 14 01 25

**Comment by trouni** [comment]
Oh yeah I like that 👍 
Could you make a PR with that fix?

**Comment by dmbf29** [comment]
ah crap i just did it in the browser. yeah ok...

**Review by dmbf29 — APPROVED** [review]
here goes nothing 🚀

**Pull request merged**
