### PR TITLE
hard coded header

### LINKED ISSUE #15: Implement component: Header
Predictor_Mockups__Copy_

### PR DESCRIPTION
**Pull request by dmbf29**
Closes #15 

*Mobile View*
Screen Shot 2021-05-24 at 21 01 14

*Desktop View*
Screen Shot 2021-05-24 at 21 01 39

### CODE REVIEW

**Comment by dmbf29** [comment]
still connected to Slack?

**Comment by trouni** [comment]
Have you used [Tailwind](https://tailwindcss.com/) before? It's the best CSS framework I've seen so far, purely based on utility classes and super easy to use/learn (docs are great and I don't think it will slow down implementation).

Since you're also taking the utility class approach, I was going to say that we should create a single stylesheet file to be able to re-use utility classes, but then it makes more sense to use Tailwind, which does exactly that. What do you think?

**Comment by dmbf29** [comment]
I'm open to either honestly. It felt a bit wrong doing it in the scoped CSS. not sure why i added the spacer one and not the padding/margin ones

**Review by trouni — APPROVED** [review]
We can merge these and convert to Tailwind later.

**Pull request merged**
