### PR TITLE
starting with register if you're not logged in on a join link

### PR DESCRIPTION
**Pull request by dmbf29**

### CODE REVIEW

**Review by trouni — CHANGES_REQUESTED** [review]
Instead, you can simply initialize the `register` data on line 52 with:
```
!!location.search.split('redirectFrom=')[1].match(/join/)
```

**Comment by dmbf29** [comment]
Doesn't seem to like that 🤔 
```
 Property or method "register" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.
 ```

**Comment by trouni** [comment]
Seems to have issues with the `split(...)[1]` when there is no query string.

This should work:
```
!!location.search.match(/join/)
```

Or this would be more specific:
```
!!location.search.match(/redirectFrom=%2Fjoin/)
```

**Comment by dmbf29** [comment]
@trouni this seems to work now with your line 💪

**Review by trouni — APPROVED** [review]

**Pull request merged**
