### PR TITLE
Fix swiper height

### PR DESCRIPTION
**Pull request by trouni**

### CODE REVIEW

**Comment by trouni** [comment]
@dmbf29 Can you check on your phone with the [preview link](https://deploy-preview-193--octacle.netlify.app/)?

**Comment by dmbf29** [comment]
IMG_5499

yeah better @trouni

**Comment by trouni** [comment]
Seems like it's better like this?

https://user-images.githubusercontent.com/34345789/202904487-ca7b2686-6a53-449c-8afa-1257c41b958d.MP4

**Comment by trouni** [comment]
Can you approve it if it's ok so that I can merge?

**Comment by trouni** [comment]
I've removed the branch protection to merge :)

**Pull request merged**
